# Generated by Django 2.2.27 on 2022-03-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
    ]
